services:
  postgres:
    image: postgres:17
    container_name: mediapot_postgres
    restart: always
    environment:
      POSTGRES_USER: mediapotadmin
      POSTGRES_PASSWORD: /Pass@098/
      POSTGRES_DB: mediapot_db
    ports:
      - "5435:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  postgres_keycloak:
    image: postgres:17
    container_name: mediapot_postgres_keycloak
    restart: always
    environment:
      POSTGRES_USER: mediapotadmin
      POSTGRES_PASSWORD: /Pass@098/
      POSTGRES_DB: mediapot_keycloak
    ports:
      - "5436:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_keycloak_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    command: -configFiles=/flyway/conf/flyway.dev.conf migrate
    volumes:
      - ./db/migrations:/flyway/sql
      - ./db/configs/:/flyway/conf/
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: mediapost_keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/mediapot_keycloak
      KC_DB_USERNAME: mediapotadmin
      KC_DB_PASSWORD: /Pass@098/
      KC_HOSTNAME: localhost
    ports:
      - "8085:8080"
    depends_on:
      - postgres_keycloak
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

volumes:
  postgres_data:
  postgres_keycloak_data:
